package cn.jsonpop.edblog.service.common.test.entity;

import java.util.Date;

public class EdUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ed_users.ID
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ed_users.user_login
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    private String userLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ed_users.user_pass
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    private String userPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ed_users.user_nicename
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    private String userNicename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ed_users.user_email
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ed_users.user_registered
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    private Date userRegistered;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ed_users.user_status
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    private Integer userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ed_users.user_pic
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    private String userPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ed_users.ID
     *
     * @return the value of ed_users.ID
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ed_users.ID
     *
     * @param id the value for ed_users.ID
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ed_users.user_login
     *
     * @return the value of ed_users.user_login
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public String getUserLogin() {
        return userLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ed_users.user_login
     *
     * @param userLogin the value for ed_users.user_login
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin == null ? null : userLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ed_users.user_pass
     *
     * @return the value of ed_users.user_pass
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ed_users.user_pass
     *
     * @param userPass the value for ed_users.user_pass
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass == null ? null : userPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ed_users.user_nicename
     *
     * @return the value of ed_users.user_nicename
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public String getUserNicename() {
        return userNicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ed_users.user_nicename
     *
     * @param userNicename the value for ed_users.user_nicename
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public void setUserNicename(String userNicename) {
        this.userNicename = userNicename == null ? null : userNicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ed_users.user_email
     *
     * @return the value of ed_users.user_email
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ed_users.user_email
     *
     * @param userEmail the value for ed_users.user_email
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ed_users.user_registered
     *
     * @return the value of ed_users.user_registered
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public Date getUserRegistered() {
        return userRegistered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ed_users.user_registered
     *
     * @param userRegistered the value for ed_users.user_registered
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public void setUserRegistered(Date userRegistered) {
        this.userRegistered = userRegistered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ed_users.user_status
     *
     * @return the value of ed_users.user_status
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ed_users.user_status
     *
     * @param userStatus the value for ed_users.user_status
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ed_users.user_pic
     *
     * @return the value of ed_users.user_pic
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public String getUserPic() {
        return userPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ed_users.user_pic
     *
     * @param userPic the value for ed_users.user_pic
     *
     * @mbg.generated Sun Dec 16 02:48:51 CST 2018
     */
    public void setUserPic(String userPic) {
        this.userPic = userPic == null ? null : userPic.trim();
    }
}